### ISSUE TITLE
文章预发布准备工作

### ISSUE THREAD

**Issue by ShixiangWang** [openbiox/UCSCXenaShiny#81]
暂时以预发表为主，提供一个引用源和成果项目。

- [ ] 收集所有参与者及导师/公司所在单位等信息
- [ ] 摘要与全文撰写
- [ ] 示例图准备

参与作者按贡献排序。通讯等以讨论后决定。

**Comment by ShixiangWang** [comment]
@Byronxy 抽空提供一篇 NAR 作为格式参考？

**Comment by ShixiangWang** [comment]
我再 @Byronxy 你一下，抽空提供一篇 NAR 作为格式参考？

**Comment by ShixiangWang** [comment]
请本项目所有参与人员看到该信息后**检查和提供个人学校/单位信息（ORCID），个人导师信息（有的话且需要纳入的话）**。

@kaigu1990 @Byronxy @longfei8533 @yinlisssss @fei0810 

~~~
---
title: 'UCSCXenaShiny: an R package to ...'
authors:
- affiliation: '1, 2, 3, 4'
  name: Shixiang Wang
  orcid: 0000-0001-9855-7357
- affiliation: 5
  name: Yi Xiong
  orcid: 0000-0002-4370-9824
- affiliation: 6
  name: Kai Gu
  orcid: 0000-0002-0177-0774
- affiliation: 7
  name: Longfei Zhao
  orcid: 0000-0002-6277-0137
- affiliation: 8
  name: Yin Li
  orcid: xxx
- affiliation: 9
  name: Fei Zhao
  orcid: xxx
- affiliation: 2
  name: Xuesong Liu
  orcid: 0000-0002-7736-0077
date: "22 June 2020"
bibliography: paper.bib
affiliations:
- index: 1
  name: Openbiox Community
- index: 2
  name: School of Life Science and Technology, ShanghaiTech University
- index: 3
  name: Shanghai Institute of Biochemistry and Cell Biology, Chinese Academy of Sciences
- index: 4
  name: University of Chinese Academy of Sciences
---
~~~

**Comment by Byronxy** [comment]
2019-2020 每年NAR有database issues和server issues
https://academic.oup.com/nar/issue/47/W1
https://academic.oup.com/nar/issue/48/D1
Guidelines :
https://academic.oup.com/nar/pages/Ms_Prep_Database
https://academic.oup.com/nar/pages/Submission_Webserver

**Comment by Byronxy** [comment]
https://academic.oup.com/nar/article/48/D1/D34/5581730
以这篇为例，就是图表的内容一般就是流程图+项目介绍

**Comment by kaigu1990** [comment]
ORCID已检查，单位写"Roche Diagnostics (Shanghai) Limited"即可，多谢了~

**Comment by Byronxy** [comment]
修改一下以及更新一下作者信息
---
title: 'UCSCXenaShiny: an R package to ...'
authors:
- affiliation: '1, 2, 3, 4'
  name: Shixiang Wang
  orcid: 0000-0001-9855-7357
- affiliation: '1, 5, 6'
  name: Yi Xiong
  orcid: 0000-0002-4370-9824
- affiliation: ‘1, 7’
  name: Kai Gu
  orcid: 0000-0002-0177-0774
- affiliation: ‘1, 8’
  name: Longfei Zhao
  orcid: 0000-0002-6277-0137
- affiliation: ‘1, 9’
  name: Yin Li
  orcid: xxx
- affiliation: ‘1, 10'
  name: Fei Zhao
  orcid: xxx
- affiliation: 6
 name: Xuejun Li
 orcid: 0000-0001-6406-4423
- affiliation: 2
  name: Xuesong Liu
  orcid: 0000-0002-7736-0077

date: "23 June 2020"
bibliography: paper.bib
affiliations: 
- index: 1
  name: Openbiox Community
- index: 2
  name: School of Life Science and Technology, ShanghaiTech University
- index: 3
  name: Shanghai Institute of Biochemistry and Cell Biology, Chinese Academy of Sciences
- index: 4
  name: University of Chinese Academy of Sciences
- index: 5
  name: Xiangya School of Medicine, Central South Univeristy
- index: 6
  name: Department of neurosurgery, Xiangya Hospital, Central South University
- index: 7
  name: Roche Diagnostics (Shanghai) Limited
---

**Comment by ShixiangWang** [comment]
/remind me to finish this process in a month

**Comment by fei0810** [comment]
这就要变成文章了么，有点强。

```

---
title: 'UCSCXenaShiny: an R package to ...'
authors:
- affiliation: '1, 2, 3, 4'
  name: Shixiang Wang
  orcid: 0000-0001-9855-7357
- affiliation: '1, 5, 6'
  name: Yi Xiong
  orcid: 0000-0002-4370-9824
- affiliation: ‘1, 7’
  name: Kai Gu
  orcid: 0000-0002-0177-0774
- affiliation: ‘1, 8’
  name: Longfei Zhao
  orcid: 0000-0002-6277-0137
- affiliation: ‘1, 9’
  name: Yin Li
  orcid: xxx
- affiliation: ‘1, 4, 9'
  name: Fei Zhao
  orcid: 0000-0002-9087-5243
- affiliation: 6
 name: Xuejun Li
 orcid: 0000-0001-6406-4423
- affiliation: 2
  name: Xuesong Liu
  orcid: 0000-0002-7736-0077

date: "23 June 2020"
bibliography: paper.bib
affiliations: 
- index: 1
  name: Openbiox Community
- index: 2
  name: School of Life Science and Technology, ShanghaiTech University
- index: 3
  name: Shanghai Institute of Biochemistry and Cell Biology, Chinese Academy of Sciences
- index: 4
  name: University of Chinese Academy of Sciences
- index: 5
  name: Xiangya School of Medicine, Central South University
- index: 6
  name: Department of Neurosurgery, Xiangya Hospital, Central South University
- index: 7
  name: Roche Diagnostics (Shanghai) Limited
- index: 8
  name: Zhengzhou University
- index: 9
  name: CAS Center for Excellence in Molecular Plant Sciences

---
```
